### ISSUE TITLE
[BUG] MUX relays don`t work correct

### ISSUE THREAD

**Issue by blevkivskyi-everstake** [Commit-Boost/commit-boost-client#217]
### Describe the bug
I want to split a batch of keys using multiple mux and mux relays. However, when I checked how it sends requests to the relays, I noticed that all the keys are being sent to all the relays, which shouldn't happen. What's even stranger is that one of the relays I don't use at all.

### To Reproduce
Run in docker with the config below
My cb-config.toml
```toml
chain = "Holesky"
[pbs]
docker_image = "ghcr.io/commit-boost/pbs:v0.4.0"
with_signer = false
host = "127.0.0.1"
port = 18550
relay_check = true
wait_all_registrations = true
timeout_get_header_ms = 950
timeout_get_payload_ms = 4000
timeout_register_validator_ms = 3000
skip_sigverify = false
min_bid_eth = 0
relay_monitors = []
late_in_slot_time_ms = 2000
#extra_validation_enabled = false
#rpc_url = "https://ethereum-holesky-rpc.publicnode.com"
[[relays]]
id = "holesky.titanrelay.xyz"
url = "https://0xaa58208899c6105603b74396734a6263cc7d947f444f396a90f7b7d3e65d102aec7e5e5291b27e08d02c50a050825c2f@holesky.titanrelay.xyz"
enable_timing_games = false
target_first_request_ms = 200
frequency_get_header_ms = 300
[[relays]]
id = "bloxroute.holesky.blxrbdn.com"
url = "https://0x821f2a65afb70e7f2e820a925a9b4c80a159620582c1766b1b09729fec178b11ea22abb3a51f07b288be815a1a2ff516@bloxroute.holesky.blxrbdn.com"
[[relays]]
id = "boost-relay-holesky.flashbots.net"
url = "https://0xafa4c6985aa049fb79dd37010438cfebeb0f2bd42b115b89dd678dab0670c1de38da0c4e9138c9290a398ecd9a0b3110@boost-relay-holesky.flashbots.net"
[[mux]]
id = "test_mux"
validator_pubkeys = [
    "0xa9aa8ccfb0c285e406beae0457807784ffc372f32e2be630d8fc00a288f723836358346fe29a47c2e22b404c56075136",
    "0xb54c27f5ca6823418c47b44ded8a89174041a4679654d20c270fcdcb73e2d6ef31226d177672cb43cb2ef5445791ec6f",
    "0xaec770f71f53173c3505912efbfa0c4590a27c271a7fbea9321cb99f3b94a2f55a87a6aca39b2f65078e257a71eef6ad",
    "0x86948c0cd567e6a6090f9b2ac35783f703e08bc22460d021722fda0f9387fc717db2638a9dbaa7d9a2f375acd4a1ad30",
    "0x85932f2048efa784d0392d2156539966dfdfdfc29d4e133eb51161a6069f59ad9c466bbe947ed6c8c5de3fed46671181",
    "0xb10bff5b485e792b4eafc3fd5821eed434ca3c6e1ef9877f5058743175f2434b65206ff649772f30eff1d4d2a17e98a8",
    "0x8fffd1319ad944ddedd7e231e6ce752b88d7804f246242d94cabbd9b1eaa401abe7879f691dedcc4894615c4af73bb23",
    "0x95108d550e3ac9da1de0758120c7122acd54c9778b3b11456d112c8ca82e209d1960964024ed1f9b03658625c8bd900b",
    "0xb2edb59a27a3cbc368bf4ab7ccf28bf19dde02cbf1d6d81951ae95040e18ea57a9cbe737de551e32475d7a95cdf6196d",
    "0xb44d4ff8796923991d1eaa7ead21d4e73ce25f37c00bf4e794bf38e3562cecd6d9bec2d5a81596feac23569471dce1bb",
    "0x90fac9457fdba4f5c5d60c240b0a1da5e4fa1b142a927aa51414256cf6999464c2b25ef4b30150988d02d46f6930d982",
    "0x8bb3aaf877575d281d6d61c7094d027c40fb62830980c1305a44263867a563c697a2f4809181020918fbb8c9f4c144a6",
]
[[mux.relays]]
id = "bloxroute.holesky.blxrbdn.com"
[[mux]]
id = "test_mux_2"
validator_pubkeys = [
    "0x812b81334174758d2d561fde424f1319d97819bf67fa019c3abf29e103f7e81501fd27ec9f592aec8dd3e40de27fd634",
    "0x94fa1a7b97f0a853bb01141688a4764d6a4d271e2d0335d2ba2c3ce5851c6e31ff0620a9ab720d8d1db4a4b8c6044d41",
    "0x8dc08def18cf3eb4a4aaa7f1c48ad0d8672259f6d64f0aa2a3fdf4477cfd701289f73cddea84f2d732824d5435537644",
    "0x9816aff1953db5f8bae1810f246cdc6837e498a1582e58fb89b49e7541fbd85179b36f7c07b2e165cccff68f84fcd98e",
    "0xaed909a80dcddb515a677810161f49c837cf6978e1753bb5cf06a5e8f1f83dc142e8334d98451748d4ecd7d9ce875035",
    "0xa016f27070deeca643f0d59b104da5ba4be4de657c60526821133df08009537bae3c2361ee55624ed4a238d4e98112d1",
    "0xb28dbbcec926781dcc028c0601ffbb0df6316ba41fac800ffd650e9b8b00414fc34a0c77ba78299883aab9254ca1554a",
    "0x8df15edec39b1fdc2cf038c49baf595f1a4b02ffd98078aaf702ae61c105b0c96f819638df18a2b73b4a1221427ba706",
    "0x95236464ae54860b84196f2ba925f9b688196939e2d10db03abb05ba3e9d7ca78dfc1ca0c2bb30bbfeeb55f24ab8fad1",
    "0xb45c4ccf59516cbbc3970815efcc6018bd1b600564ec3bf0091b1a341a27a35f625f5686cabd4ba4798cc7e4d6851996",
    "0xb1963839c087634d53a37a1ee8389d6341deee270f3240863a3ec0890b9a2a6566b5b2ef68bcff7a1c825cb1c2d0ca93",
    "0x8ab2d7b99668f4339f0c4873a32c5cd9cadad6315d3340933e6ea9d560b6035a352e3dd2e9160c09a128de200af7f5cc",
]
[[mux.relays]]
id = "boost-relay-holesky.flashbots.net"
```
docker-compose file
```
services:
  commit_boost:
    container_name: commit_boost
    environment:
      CB_CONFIG: /cb-config.toml
      CB_METRICS_PORT: "18555"
      CB_PBS_ENDPOINT: 0.0.0.0:18550
    healthcheck:
      test:
        - CMD-SHELL
        - (echo > /dev/tcp/localhost/18550) >/dev/null 2>&1 && exit 1 || exit 0
      timeout: 5s
      interval: 10s
      retries: 5
    image: ghcr.io/commit-boost/pbs:v0.4.0
    networks:
      default: null
    ports:
      - mode: ingress
        target: 18550
        published: "18550"
        protocol: tcp
      - mode: ingress
        target: 18555
        published: "18555"
        protocol: tcp
    restart: always
    user: "1000"
    volumes:
      - type: bind
        source: /mnt/operational/eth-docker/cb-config.toml
        target: /cb-config.toml
        read_only: true
        bind: {}
      - type: bind
        source: /mnt/operational/eth-docker/logs
        target: /var/logs/commit-boost
        bind: {}
```
### Expected behavior
For every relay own request
### Screenshots
![image](https://github.com/user-attachments/assets/3a28b22f-8703-4bd7-9744-14e2228017d3)
![image](https://github.com/user-attachments/assets/11351c5d-23a8-4074-9792-aeff5f766452)

### Environment information
Docker version 27.4.0, build bde2b89

Docker image ghcr.io/commit-boost/pbs:v0.4.0
