### ISSUE TITLE
Add the ability to specify explicit get parameters to relayers

### ISSUE THREAD

**Issue by aimxhaisse** [Commit-Boost/commit-boost-client#289]
Some relayers use HTTP GET parameters to configure some settings (authentication on bloxroute, timing games settings on aestus). Specifying them directly in the URL doesn't work as the URL is parsed and get parameters are removed.

It'd be good to add a new `get_params` setting, similar to the `headers` setting of relayers, which has the same purpose and semantics:

```
- id: "mainnet-flashbots"
  url: "https://xxx.yy.zz" 
  get_params:
      headerDelay: "0"
 ```

Would append to all relayer calls `?headerDelay=0`

I have a PR coming for this (already tested at scale on mainnet).
